version: '3.0'

expectations:
  population_size: 10000

actions:

  gen_std_popn:
    run: cohortextractor:latest generate_cohort --study-definition study_definition
    outputs:
      highly_sensitive:
        cohort: output/input.csv

  run_model:
    run: r:latest analysis/1-rcmdbatch.R # 1-basic-rd.R
    needs: [gen_std_popn]
    outputs:
      moderately_sensitive:
        figure1: output/plots/cd_plot.png
        # figure2: output/plots/four_plot.png
        log: logs/1-basic-rd.log

# generate_cohort_rd_by_week:
#     run: cohortextractor:latest generate_cohort --study-definition study_definition_3_activity --index-date-range "2020-12-08 to 2021-02-01 by week" --output-dir=output/measures
#     outputs:
#       highly_sensitive:
#         cohort: output/measures/input_3_activity_*.csv